name: github-activity

on:
  workflow_dispatch:
  schedule:
    - cron: "7 2 * * *"   # daily at 02:07 UTC (off-peak)
  push:
    paths:
      - ".github/workflows/github-activity.yml"
      - "scripts/generate-gh-contribs.js"

permissions:
  contents: write

env:
  LOGIN: "evanniko1"
  OUT_DIR: "images"
  LIGHT_NAME: "github-activity-light.svg"
  DARK_NAME: "github-activity-dark.svg"
  TITLE: "GitHub contributions calendar for Evangelos Nikolados"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate SVGs via GitHub GraphQL API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN: ${{ env.LOGIN }}
          OUT_DIR: ${{ env.OUT_DIR }}
          LIGHT_NAME: ${{ env.LIGHT_NAME }}
          DARK_NAME: ${{ env.DARK_NAME }}
          TITLE: ${{ env.TITLE }}
        run: |
          node scripts/generate-gh-contribs.js \
            --login "$LOGIN" \
            --out "$OUT_DIR" \
            --light "$LIGHT_NAME" \
            --dark "$DARK_NAME" \
            --title "$TITLE"

      - name: Commit & push if changed
        run: |
          set -e
          git add "${{ env.OUT_DIR }}/${{ env.LIGHT_NAME }}" "${{ env.OUT_DIR }}/${{ env.DARK_NAME }}"
          if ! git diff --staged --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(gh-activity): refresh contributions calendar SVGs"
            git push
          else
            echo "No changes to commit"
          fi
