name: Update GitHub Activity SVG

on:
  schedule:
    # Update daily at 03:37 UTC (staggered to avoid rate-limit contention)
    - cron: "37 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: github-activity
  cancel-in-progress: false

jobs:
  build:
    name: Fetch & recolor contributions calendar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create temp dir
        run: mkdir -p images/_tmp

      - name: Fetch raw contributions page (HTML)
        run: |
          curl -fsSL \
            -H "Accept: text/html" \
            -H "User-Agent: Mozilla/5.0 (compatible; GitHubActions)" \
            -L "https://github.com/users/evanniko1/contributions" \
            -o images/_tmp/contrib.html

      - name: Extract the <svg> only and create light/dark variants
        run: |
          # Extract the first <svg>…</svg> block from the HTML
          sed -n '/<svg[[:space:]]/ , /<\/svg>/p' images/_tmp/contrib.html > images/github-activity-light.svg

          # Ensure it’s a valid standalone SVG (optional XML header)
          if ! head -n1 images/github-activity-light.svg | grep -q '<?xml'; then
            sed -i '1s|^|<?xml version="1.0" encoding="UTF-8"?>\n|' images/github-activity-light.svg
          fi

          # Duplicate for dark theme
          cp images/github-activity-light.svg images/github-activity-dark.svg

      - name: Recolor SVGs to site palette
        shell: bash
        run: |
          # Original GitHub heatmap colors (for reference):
          # #ebedf0 (empty), #9be9a8, #40c463, #30a14e, #216e39 (highest)

          # Light theme → teal scale
          sed -i \
            -e 's/#ebedf0/#e7f2f2/g' \
            -e 's/#9be9a8/#bfe6e6/g' \
            -e 's/#40c463/#77c9c9/g' \
            -e 's/#30a14e/#2aa5a5/g' \
            -e 's/#216e39/#0e6d6d/g' \
            images/github-activity-light.svg

          # Dark theme → darker teal scale + higher-contrast labels if present
          sed -i \
            -e 's/#ebedf0/#0f1b1b/g' \
            -e 's/#9be9a8/#1f5c5c/g' \
            -e 's/#40c463/#2f8c8c/g' \
            -e 's/#30a14e/#46b5b5/g' \
            -e 's/#216e39/#7cdcdc/g' \
            images/github-activity-dark.svg

          # Improve text/axis contrast on dark
          sed -i \
            -e 's/fill="#24292e"/fill="#e6e6e6"/g' \
            -e 's/fill="#57606a"/fill="#c9c9c9"/g' \
            images/github-activity-dark.svg

          rm -rf images/_tmp

      - name: Commit updated SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(gh-activity): refresh contributions calendar SVGs"
          file_pattern: images/github-activity-*.svg
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
